import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
import { useState } from 'react'
import { Media } from "@/types/anilist";
import { getList } from '@/api/anilist'
import useApi from '@/hooks/useApi';
import { AnimeList } from '@/components/AnimeList';

// const inter = Inter({ subsets: ['latin'] })

function IsLoading() {
  return <div>Is loading</div>
}

export default function Home() {
  const [media, setMedia] = useState<Media[]>([])
  const { isLoading, error } = useApi(async () => {
    const result = await getList({ perPage: 10 });

    if (result != null) {
      setMedia(result.data.Page.media);
    }
  });

  return (
    <>
      <Head>
        <title>Anihyou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 pt-10 pb-20 max-w-screen-2xl m-auto">
        {isLoading && <IsLoading />}
        <AnimeList media={media} />
      </main>
    </>
  );
}
